In [1]:
import numpy as np

# 1D array with numbers from 1 to 10
array_1d = np.arange(1, 11)

# 2D array (3x3) with random integers (between 1 and 100)
array_2d = np.random.randint(1, 101, size=(3, 3))

print("1D Array:", array_1d)
print("2D Array:\n", array_2d)

1D Array: [ 1  2  3  4  5  6  7  8  9 10]
2D Array:
 [[49 21  2]
 [82  1 51]
 [42 18 31]]


In [2]:
# Calculations
total_sum = np.sum(array_1d)
mean_val = np.mean(array_1d)
max_val = np.max(array_1d)

# Vectorized multiplication (multiplies every element)
multiplied_array = array_1d * 2

# Conditional replacement (Boolean Indexing)
# We create a copy so we don't overwrite the original array_1d
task_array = array_1d.copy()
task_array[task_array > 5] = 0

print(f"Sum: {total_sum}, Mean: {mean_val}, Max: {max_val}")
print("Multiplied by 2:", multiplied_array)
print("Values > 5 replaced with 0:", task_array)

Sum: 55, Mean: 5.5, Max: 10
Multiplied by 2: [ 2  4  6  8 10 12 14 16 18 20]
Values > 5 replaced with 0: [1 2 3 4 5 0 0 0 0 0]
